"""drop mrc_item.default_qty

Revision ID: e827d8d69b10
Revises: ebcb4b96534b
Create Date: 2026-05-01 12:05:28.159666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e827d8d69b10'
down_revision: Union[str, Sequence[str], None] = 'ebcb4b96534b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mrc_item', schema=None) as batch_op:
        batch_op.drop_column('default_qty')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mrc_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_qty', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
