"""initial schema

Revision ID: ebcb4b96534b
Revises: 
Create Date: 2026-05-01 11:19:45.761126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcb4b96534b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mip_code'), ['code'], unique=True)

    op.create_table('spmig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spmig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spmig_code'), ['code'], unique=True)

    op.create_table('hazmat_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spmig_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.String(length=256), nullable=False),
    sa.Column('niin', sa.String(length=32), nullable=True),
    sa.Column('unit_of_issue', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spmig_id'], ['spmig.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hazmat_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazmat_item_spmig_id'), ['spmig_id'], unique=False)

    op.create_table('mrc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mip_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('periodicity', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mip_id'], ['mip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mip_id', 'code', name='uq_mrc_mip_code')
    )
    with op.batch_alter_table('mrc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mrc_mip_id'), ['mip_id'], unique=False)

    op.create_table('mrc_item',
    sa.Column('mrc_id', sa.Integer(), nullable=False),
    sa.Column('hazmat_item_id', sa.Integer(), nullable=False),
    sa.Column('default_qty', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hazmat_item_id'], ['hazmat_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mrc_id'], ['mrc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mrc_id', 'hazmat_item_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('datetime_of_request', sa.DateTime(), nullable=True),
    sa.Column('lpo', sa.String(length=128), nullable=True),
    sa.Column('workcenter', sa.String(length=128), nullable=True),
    sa.Column('requestor_name', sa.String(length=128), nullable=True),
    sa.Column('hazmat_location', sa.String(length=128), nullable=True),
    sa.Column('source_mip_id', sa.Integer(), nullable=True),
    sa.Column('source_mrc_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_mip_id'], ['mip.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_mrc_id'], ['mrc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('hazmat_item_id', sa.Integer(), nullable=True),
    sa.Column('spmig_code', sa.String(length=64), nullable=True),
    sa.Column('nomenclature', sa.String(length=256), nullable=True),
    sa.Column('niin', sa.String(length=32), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hazmat_item_id'], ['hazmat_item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_line_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_line_request_id'))

    op.drop_table('request_line')
    op.drop_table('request')
    op.drop_table('mrc_item')
    with op.batch_alter_table('mrc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mrc_mip_id'))

    op.drop_table('mrc')
    with op.batch_alter_table('hazmat_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazmat_item_spmig_id'))

    op.drop_table('hazmat_item')
    with op.batch_alter_table('spmig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spmig_code'))

    op.drop_table('spmig')
    with op.batch_alter_table('mip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mip_code'))

    op.drop_table('mip')
    # ### end Alembic commands ###
